export default [
  {
    id: 1,
    name: 'The Calligraphy Throne',
    badge: 'best-seller',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Calligraphy Throne is a masterpiece of artisanal precision. Its surface is finished in a striking combination of clean gloss, super black, and golden paint, all sealed beneath a silky matte lacquer that gives the piece its signature smooth, luminous touch. Presented in a rich chocolate brown finish, this table measures 48" \u00d7 30" \u00d7 17" \u2014 proportioned to command any living space with quiet, sovereign authority.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte (Sealer + Lacquer)',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'N2',
    image: '/images/1.webp',
    date_added: '2026-05-10',
    sales_rank: 4,
  },
  {
    id: 2,
    name: 'The Emerald Salon',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Emerald Salon is a refined statement of artisanal excellence. Its surface combines clean gloss, super black, and golden paint, all sealed beneath a silky matte lacquer for a smooth, luminous finish. Presented in a rich chocolate brown tone, this piece measures 48" \u00d7 30" \u00d7 17" \u2014 perfectly proportioned to elevate any living space with understated luxury.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte (Sealer + Lacquer)',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'N2',
    image: '/images/2.webp',
    date_added: '2026-05-10',
    sales_rank: 6,
  },
  {
    id: 3,
    name: 'The Imperial Arabesque',
    badge: 'best-seller',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Imperial Arabesque is a sovereign statement of dark luxury. Its surface is finished in clean gloss with a super plain black paint treatment, all sealed beneath a brilliant high gloss lacquer for a commanding mirror-like depth. Standing on imported golden feet that add a striking contrast of warmth against the rich Royal Black finish, this table measures 42" \u00d7 42" \u00d7 18" \u2014 a perfectly proportioned square silhouette that dominates any distinguished living space with quiet, regal authority.`,
    material: 'MDF + Fine Board (ZRK) with Imported Golden Foot',
    finishing: 'High Gloss',
    sizing: `42" \u00d7 42" \u00d7 18" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Royal Golden',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'BB1',
    image: '/images/3.webp',
    date_added: '2026-05-10',
    sales_rank: 2,
  },
  {
    id: 5,
    name: 'The Legacy Console',
    badge: 'best-seller',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Legacy Console is a timeless piece of artisanal distinction. Its surface is finished in clean gloss with a super plain black paint treatment, all elevated beneath a brilliant high gloss lacquer that delivers a flawless, mirror-like sheen. Presented in a refined Off White & Black Duco finish, this table measures 60" \u00d7 32" \u00d7 19" \u2014 generously proportioned to anchor any living space with quiet, enduring sophistication.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'High Gloss',
    sizing: `60" \u00d7 32" \u00d7 19" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Off White & Black (Duco)',
    top_type: 'Clean Gloss + Super Plain Black Paint',
    model_number: 'DD1',
    image: '/images/5.webp',
    date_added: '2026-05-10',
    sales_rank: 1,
  },
  {
    id: 6,
    name: 'The Imperial Marble',
    badge: 'best-seller',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF with a UV Sheet finish (ZRK), The Imperial Marble is a triumph of modern artisanal luxury. Its top surface features a stunning Marbelized UV Sheet that replicates the depth and elegance of natural marble with exceptional clarity. Finished in a radiant high gloss lacquer, the piece is presented in a sophisticated Off White & Golden palette with grey drawer detailing. Measuring 48" \u00d7 30" \u00d7 18", this table brings timeless grandeur and refined proportion to any distinguished living space.`,
    material: 'MDF + UV Sheet (ZRK)',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 18" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Off White & Golden with Grey Drawer',
    top_type: 'UV Sheet (Marbelized)',
    model_number: 'AA',
    image: '/images/6.webp',
    date_added: '2026-05-10',
    sales_rank: 3,
  },
  {
    id: 7,
    name: 'The Noir Riviera',
    badge: 'best-seller',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Noir Riviera is a statement of dark, sovereign luxury. Its surface is finished in clean gloss with a super black paint treatment, all sealed beneath a brilliant high gloss lacquer that delivers a commanding mirror-like depth. Standing on imported golden feet that add a striking contrast of warmth against the rich Royal Black finish, this table measures 48" \u00d7 30" \u00d7 17" \u2014 a generously proportioned silhouette that anchors any distinguished living space with quiet, regal authority.`,
    material: 'MDF + Fine Board (ZRK) with Imported Golden Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Royal Black',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'BB1',
    image: '/images/7.webp',
    date_added: '2026-05-10',
    sales_rank: 7,
  },
  {
    id: 8,
    name: 'The Versailles Set',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Versailles Set is a sophisticated three-piece collection built for the refined interior. The main coffee table \u2014 finished in a bold combination of clean gloss, super black, and golden paint \u2014 measures a generous 48" (L) \u00d7 30" (W) \u00d7 17" (H), commanding any living space with quiet authority. Each matching side table, sized at 24" \u00d7 24" \u00d7 16.5", echoes the same craftsmanship and proportions in perfect symmetry. Presented in a distinguished Grey and Jet Black colour scheme and sealed beneath a silky matte finish, the set delivers a luxurious surface that is as smooth to the touch as it is striking to the eye.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte',
    sizing: `Main: 48" \u00d7 30" \u00d7 17" \u00b7 Side: 24" \u00d7 24" \u00d7 16.5"`,
    color_scheme: 'Grey & Jet Black',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'V Versache',
    image: '/images/8.webp',
    date_added: '2026-05-10',
    sales_rank: 5,
  },
  {
    id: 9,
    name: 'The Urban Penthouse',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) and set on a solid foot base, The Urban Penthouse is a bold expression of contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding mirror-like depth. Presented in a refined Smoke Grey colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any modern living space with understated, architectural authority.`,
    material: 'MDF + Fine Board (ZRK) with Solid Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Smoke Grey',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'NW1',
    image: '/images/9.webp',
    date_added: '2026-05-10',
    sales_rank: 9,
  },
  {
    id: 10,
    name: 'The Emperor Gold',
    badge: 'best-seller',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Emperor Gold is adorned with intricate fiber molding pieces and set on a classic foot base \u2014 a masterwork of ornamental grandeur. Its surface is finished in clean gloss with super black and golden paint, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in an exclusive Imported Brazilian Royal Golden colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 18" (H) \u2014 a sovereign centrepiece that commands reverence in any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Piece & Classic Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 18" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Imported Brazilian Royal Golden',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'NP',
    image: '/images/10.webp',
    date_added: '2026-05-10',
    sales_rank: 8,
  },
  {
    id: 11,
    name: 'The Silver Requiem',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) and elevated on a sculptural fiber molding foot, The Silver Requiem is a masterpiece of dark, refined luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a silky matte lacquer that gives the piece its signature smooth, luminous touch. Presented in a striking Jet Black and Silver colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a commanding presence for those who find beauty in darkness and elegance in contrast.`,
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Foot',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Jet Black & Silver',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'S9',
    image: '/images/11.webp',
    date_added: '2026-05-10',
    sales_rank: 12,
  },
  {
    id: 12,
    name: 'The Forest Baron',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) and set on a classic solid foot base, The Forest Baron is a bold expression of understated luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a refined Smoke Grey colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any modern living space with quiet, architectural authority.`,
    material: 'MDF + Fine Board (ZRK) with Classic Solid Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Smoke Grey',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'B7',
    image: '/images/12.webp',
    date_added: '2026-05-10',
    sales_rank: 11,
  },
  {
    id: 13,
    name: 'The Maharaja',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on imported golden chrome feet, The Maharaja is a regal statement of refined luxury. Its surface is finished in clean gloss with super black and off white high gloss border paint, sealed beneath a brilliant high gloss lacquer that delivers a flawless, commanding depth. Presented in a distinguished Off White High Gloss colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereign centrepiece that brings timeless elegance and architectural grace to any distinguished living space.`,
    material: 'MDF (ZRK) with Imported Golden Chrome Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Off White High Gloss',
    top_type: 'Clean Gloss + Super Black & Off White High Gloss Border Paint',
    model_number: 'M1',
    image: '/images/13.webp',
    date_added: '2026-05-10',
    sales_rank: 14,
  },
  {
    id: 14,
    name: 'The Alabaster Night',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Alabaster Night is a study in dark, refined sophistication. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a silky matte lacquer that delivers a smooth, luminous touch. Presented in a sleek Smoke Grey colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 16.5" (H) \u2014 a quietly commanding presence that brings understated elegance and contemporary authority to any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 16.5" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Smoke Grey',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'BG1',
    image: '/images/14.webp',
    date_added: '2026-05-10',
    sales_rank: 13,
  },
  {
    id: 16,
    name: 'The Ivory Shadow',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) and elevated on a fiber molding classic foot, The Ivory Shadow is a masterwork of warmth and ornamental refinement. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Sheesham tone with hand-applied imported golden accents, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereignly crafted centrepiece that brings heritage warmth and artisanal grandeur to any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Classic Foot',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Sheesham & Hand Applied Imported Golden',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'S92',
    image: '/images/16.webp',
    date_added: '2026-05-10',
    sales_rank: 15,
  },
  {
    id: 17,
    name: 'The Duet',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) and set on a solid foot with an antique gold finish, The Duet is a masterpiece of warmth and timeless refinement. Its surface is dressed in a clean gloss treatment, sealed beneath a silky matte lacquer for a smooth, distinguished touch. Both the top and sides carry a hand-applied antique gold rubbing finish that brings an aged, aristocratic warmth to every surface. Measuring 48" (L) \u00d7 30" (W) \u00d7 17" (H), this table is a quietly sovereign centrepiece \u2014 one that elevates any living space with the understated grandeur of heritage craftsmanship.`,
    material: 'MDF + Fine Board (ZRK) with Solid Foot + Antique Gold Finish',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Top & Sides Antique Gold Rubbing Finish & Brown',
    top_type: 'Clean Gloss',
    model_number: 'FT',
    image: '/images/17.webp',
    date_added: '2026-05-10',
    sales_rank: 18,
  },
  {
    id: 18,
    name: 'The Golden Heritage',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF with intricate CNC carving (ZRK) and set on solid legs, The Golden Heritage is a masterwork of artisanal precision and ornamental grandeur. Its surface is dressed in a clean gloss treatment, sealed beneath a silky matte lacquer for a smooth, distinguished touch. Presented in a rich Brown and Golden colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereignly crafted centrepiece that brings heritage warmth and carved artistry to any distinguished living space.`,
    material: 'MDF + CNC Carving (ZRK) with Solid Legs',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Brown & Golden',
    top_type: 'Clean Gloss',
    model_number: 'Victoria',
    image: '/images/18.webp',
    date_added: '2026-05-10',
    sales_rank: 17,
  },
  {
    id: 19,
    name: 'The Navy Atelier',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF with intricate CNC carving (ZRK) and set on solid legs, The Navy Atelier is a bold expression of ornamental luxury. Its surface is finished in a clean gloss treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a striking Royal Gold and Antique Golden colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereignly crafted centrepiece that commands reverence in any distinguished living space.`,
    material: 'MDF + CNC Carving (ZRK) with Solid Legs',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Royal Gold & Antique Golden',
    top_type: 'Clean Gloss',
    model_number: 'SS',
    image: '/images/19.webp',
    date_added: '2026-05-10',
    sales_rank: 20,
  },
  {
    id: 20,
    name: 'The Versailles Set II',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF with an intricate CNC tree motive (ZRK), The Versailles Set II is a masterpiece of nature-inspired artisanal carving. Its surface is dressed in a clean gloss treatment, sealed beneath a silky matte lacquer for a smooth, distinguished touch. Presented in a rich Chocolate Brown colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereignly crafted centrepiece that brings organic warmth and carved artistry to any distinguished living space.`,
    material: 'MDF + CNC Tree Motive (ZRK)',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown',
    top_type: 'Clean Gloss',
    model_number: 'RT',
    image: '/images/20.webp',
    date_added: '2026-05-10',
    sales_rank: 19,
  },
  {
    id: 21,
    name: 'The Sovereign Set',
    badge: 'best-seller',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF with intricate CNC flower carving and sumptuous silk fabric detailing (ZRK), The Sovereign Set is a masterwork of ornamental refinement and tactile luxury. Its surface is dressed in a clean gloss treatment, sealed beneath a silky matte lacquer for a smooth, distinguished touch. Presented in a rich Chocolate Brown colour scheme, this piece measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereignly crafted centrepiece that brings heritage warmth, carved artistry, and silk elegance to any distinguished living space.`,
    material: 'MDF + CNC With Silk Fabric (ZRK)',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown',
    top_type: 'Clean Gloss',
    model_number: 'RT',
    image: '/images/21.webp',
    date_added: '2026-05-10',
    sales_rank: 22,
  },
  {
    id: 22,
    name: 'The Marble Throne',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) and elevated on a sculptural fiber molding foot, The Marble Throne is a masterpiece of dark, refined luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a silky matte lacquer that gives the piece its signature smooth, luminous touch. Presented in a striking Jet Black and Silver colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a commanding presence for those who find beauty in darkness and elegance in contrast.`,
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Foot',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Jet Black & Silver',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'S9',
    image: '/images/22.webp',
    date_added: '2026-05-10',
    sales_rank: 21,
  },
  {
    id: 23,
    name: 'The Obsidian Baron',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) and set on a solid foot base, The Obsidian Baron is a bold expression of contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding mirror-like depth. Presented in a refined Smoke Grey colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any modern living space with understated, architectural authority.`,
    material: 'MDF + Fine Board (ZRK) with Solid Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Smoke Grey',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'NW1',
    image: '/images/23.webp',
    date_added: '2026-05-10',
    sales_rank: 24,
  },
  {
    id: 24,
    name: 'The Oval Reeded',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Oval Reeded is a refined four-stool coffee table set built for both elegance and everyday living. Its MDF top surface is sealed beneath a silky matte lacquer that delivers a smooth, distinguished finish. Presented in a sophisticated Two Tone Brown colour scheme, this set measures 42" (L) \u00d7 42" (W) \u00d7 18" (H) \u2014 a perfectly proportioned square silhouette that brings warmth, versatility, and artisanal character to any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte',
    sizing: `42" \u00d7 42" \u00d7 18" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Two Tone Brown',
    top_type: 'MDF',
    model_number: '4 Stools Coffee Table',
    image: '/images/24.webp',
    date_added: '2026-05-10',
    sales_rank: 23,
  },
  {
    id: 25,
    name: 'The Sovereign Set II',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Sovereign Set II is a bold statement of dark, contemporary luxury. Its surface is dressed in a clean gloss treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a striking Jet Black and Golden Drawer colour scheme, this piece measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereignly crafted centrepiece that brings dramatic contrast and refined elegance to any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Jet Black & Golden Drawer',
    top_type: 'Clean Gloss',
    model_number: 'B2',
    image: '/images/25.webp',
    date_added: '2026-05-10',
    sales_rank: 26,
  },
  {
    id: 26,
    name: 'The Timber Oval',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on imported chrome gold feet, The Timber Oval is a striking expression of modern luxury. Its top surface features a stunning white marbelized high gloss finish that replicates the depth and elegance of natural marble with exceptional clarity. Presented in a refined Swik and White Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 18" (H) \u2014 perfectly proportioned to command any distinguished living space with timeless grandeur and polished sophistication.`,
    material: 'MDF (ZRK) with Imported Chrome Gold Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 18" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Swik & White (Duco)',
    top_type: 'White Marbelized High Gloss',
    model_number: 'Round.C',
    image: '/images/26.webp',
    date_added: '2026-05-10',
    sales_rank: 25,
  },
  {
    id: 27,
    name: 'The Sovereign Set V',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) and elevated on ornate fiber molding golden feet, The Sovereign Set V is a bold declaration of dark, regal luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a striking Royal Golden and Jet Black Duco colour scheme, this piece measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereignly crafted centrepiece that commands reverence and brings dramatic grandeur to any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Golden Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Royal Golden & Jet Black (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'Double TT',
    image: '/images/27.webp',
    date_added: '2026-05-10',
    sales_rank: 28,
  },
  {
    id: 28,
    name: 'The Cream Oval',
    badge: '',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Cream Oval is a refined expression of contemporary sophistication. Its surface is finished in clean gloss with a grey and super black paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in an elegant Smoke Grey Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to bring understated elegance and quiet architectural authority to any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Smoke Grey (Duco)',
    top_type: 'Clean Gloss + Grey & Super Black Paint',
    model_number: 'C2',
    image: '/images/28.webp',
    date_added: '2026-05-10',
    sales_rank: 27,
  },
  {
    id: 30,
    name: 'The Silver Salon',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on a sculptural fiber molding foot, The Silver Salon is a bold expression of dark, contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a distinguished Grey and Black Antique Duco colour scheme, this piece measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with understated architectural authority and refined elegance.`,
    material: 'MDF (ZRK) with Fiber Molding Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Grey & Black Antique (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'FFN',
    image: '/images/30.webp',
    date_added: '2026-05-15',
    sales_rank: 5,
  },
  {
    id: 31,
    name: 'The Pearl Regent',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on an ornate fiber molding foot with hand-applied golden detailing, The Pearl Regent is a regal statement of refined luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a flawless, commanding depth. Presented in a distinguished Off White and Black Antique Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereignly crafted centrepiece that brings timeless elegance and artisanal grandeur to any distinguished living space.`,
    material: 'MDF (ZRK) with Fiber Molding Hand Applied Golden Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Off White & Black Antique (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'WB1',
    image: '/images/31.webp',
    date_added: '2026-05-15',
    sales_rank: 2,
  },
  {
    id: 32,
    name: 'The Ivory Drum',
    badge: 'new',
    category: 'Coffee Tables',
    description: `A bold round drum silhouette entirely wrapped in fine white reeding, topped with a polished black glass surface and elevated on slender polished gold ring legs. The Ivory Drum brings organic, sculptural form to the luxury living room \u2014 a piece that invites touch and rewards every viewing angle with a new moment of beauty.`,
    material: 'White Reeded Drum Body & Polished Black Glass Top with Gold Ring Legs',
    finishing: 'High Gloss',
    sizing: '90 cm Diameter \u00d7 45 cm H',
    color_scheme: 'White Reeded, Black Glass, Gold',
    top_type: 'Polished Black Glass',
    model_number: '',
    image: '/images/32.webp',
    date_added: '2026-05-15',
    sales_rank: 4,
  },
  {
    id: 33,
    name: 'The Latte Luxe',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on imported golden chrome feet, The Latte Luxe is a striking expression of contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in an exclusive Metallic Champion Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with understated glamour and sovereign authority.`,
    material: 'MDF (ZRK) with Imported Golden Chrome Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Metallic Champion (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: '4D',
    image: '/images/33.webp',
    date_added: '2026-05-15',
    sales_rank: 7,
  },
  {
    id: 34,
    name: 'The Phantom Steel',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on an ornate fiber molding foot with hand-applied golden detailing, The Phantom Steel is a bold expression of dark, contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in an exclusive Metallic Dark Grey Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with understated power and sovereign authority.`,
    material: 'MDF (ZRK) with Fiber Molding Hand Applied Golden Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Metallic Dark Grey (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'WB2',
    image: '/images/34.webp',
    date_added: '2026-05-15',
    sales_rank: 9,
  },
  {
    id: 35,
    name: 'The Twilight',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and set on a solid foot with a distinctive swick paint finish, The Twilight is a bold expression of dark, contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a striking Black and Swick Metallic Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with dramatic elegance and sovereign authority.`,
    material: 'MDF (ZRK) with Solid Foot Swick Paint',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Black & Swick Metallic (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'Aroma',
    image: '/images/35.webp',
    date_added: '2026-05-15',
    sales_rank: 6,
  },
  {
    id: 36,
    name: 'The Grand Salon',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on imported golden chrome feet, The Grand Salon is a regal expression of opulent contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a stunning Royal Gold Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with timeless grandeur and sovereign authority.`,
    material: 'MDF (ZRK) with Imported Golden Chrome Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Royal Gold (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'SDD',
    image: '/images/36.webp',
    date_added: '2026-05-15',
    sales_rank: 1,
  },
  {
    id: 37,
    name: 'The Golden Baroque Trio',
    badge: 'new',
    category: 'Coffee Sets',
    description: `Crafted from premium MDF (ZRK) and elevated on ornate fiber molding feet, The Golden Baroque Trio is a magnificent three-piece set built for the grandest of interiors. Each piece is finished in clean gloss with a super black and golden paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a regal Royal Golden Antique Duco colour scheme, the main table measures 42" (L) \u00d7 42" (W) \u00d7 18" (H) while the two matching side tables each measure 24" (L) \u00d7 24" (W) \u00d7 17" (H) \u2014 a sovereignly crafted ensemble that transforms any distinguished living space into a salon of extraordinary grandeur.`,
    material: 'MDF (ZRK) with Fiber Molding Foot \u2014 3-Piece Set',
    finishing: 'High Gloss',
    sizing: `Main: 42" \u00d7 42" \u00d7 18" \u00b7 Side: 24" \u00d7 24" \u00d7 17"`,
    color_scheme: 'Royal Golden Antique (Duco)',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'FP1 Set',
    image: '/images/37.webp',
    date_added: '2026-05-15',
    sales_rank: 8,
  },
  {
    id: 38,
    name: 'The Ivory Stripes',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on an ornate fiber molding foot, The Ivory Stripes is a refined expression of elegant contrast and artisanal luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a distinguished Off White and Golden Voinal Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with timeless sophistication and sovereign authority.`,
    material: 'MDF (ZRK) with Fiber Molding Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Off White & Golden Voinal (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'WB3',
    image: '/images/38.webp',
    date_added: '2026-05-15',
    sales_rank: 11,
  },
  {
    id: 39,
    name: 'The Champagne Salon',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on imported golden feet, The Champagne Salon is a refined expression of contemporary opulence. Featuring a practical double drawer design, its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in an exclusive Golden Swick Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with understated glamour and sovereign authority.`,
    material: 'MDF (ZRK) with Imported Golden Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Golden Swick (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'KK with Double Drawer',
    image: '/images/39.webp',
    date_added: '2026-05-15',
    sales_rank: 10,
  },
  {
    id: 40,
    name: 'The Bicolour Horizon',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on imported golden chrome feet, The Bicolour Horizon is a bold expression of contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a refined Smoked Grey Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with understated sophistication and sovereign authority.`,
    material: 'MDF (ZRK) with Imported Golden Chrome Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Smoked Grey (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'SDD3',
    image: '/images/40.webp',
    date_added: '2026-05-15',
    sales_rank: 12,
  },
  {
    id: 41,
    name: 'The Grey Talon',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and set on a solid foot base, The Grey Talon is a striking expression of modern luxury. Its top surface features a stunning high gloss marbelized finish that replicates the depth and elegance of natural marble with exceptional clarity, sealed beneath a brilliant high gloss lacquer for a flawless, commanding sheen. Presented in a sophisticated Off White and Smoke Grey Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with timeless grandeur and refined sophistication.`,
    material: 'MDF (ZRK) with Solid Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Off White & Smoke Grey (Duco)',
    top_type: 'High Gloss Marbelized',
    model_number: 'TGT',
    image: '/images/41.webp',
    date_added: '2026-05-15',
    sales_rank: 14,
  },
  {
    id: 43,
    name: 'The Haussmann Grand',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on imported golden feet, The Haussmann Grand is a masterwork of marble-inspired grandeur. Featuring a convenient double drawer design, its top surface showcases a stunning UV Golden Marbelized finish that replicates the depth and elegance of natural marble with exceptional clarity, sealed beneath a UV high gloss lacquer for a flawless, luminous sheen. Presented in an exquisite White and Gold Voilan Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereignly crafted centrepiece that commands timeless elegance and refined grandeur in any distinguished living space.`,
    material: 'MDF (ZRK) with Imported Golden Foot',
    finishing: 'UV High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'White & Gold Voilan (Duco)',
    top_type: 'UV Golden Marbelized',
    model_number: 'KK4 with Double Drawer',
    image: '/images/43.webp',
    date_added: '2026-05-15',
    sales_rank: 16,
  },
  {
    id: 44,
    name: 'The Silver Duke',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF (ZRK) and elevated on an ornate fiber molding foot, The Silver Duke is a bold declaration of monochrome luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a striking Metallic Silver and Jet Black Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with dramatic contrast, contemporary edge, and sovereign authority.`,
    material: 'MDF (ZRK) with Fiber Molding Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Metallic Silver & Jet Black (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'SD1',
    image: '/images/44.webp',
    date_added: '2026-05-15',
    sales_rank: 15,
  },
  {
    id: 46,
    name: 'The Mughal Trio',
    badge: 'new',
    category: 'Coffee Sets',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Mughal Trio is a masterwork of ornamental grandeur and artisanal refinement. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Featuring an exquisite golden double drawer, this table is presented in a rich Chocolate Brown and Golden Duco colour scheme and measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sovereignly crafted centrepiece that brings heritage warmth, golden artistry, and distinguished elegance to any living space.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown & Golden (Duco)',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'TMT with Golden Double Drawer',
    image: '/images/46.webp',
    date_added: '2026-05-17',
    sales_rank: 5,
  },
  {
    id: 47,
    name: 'The Fleur Noir',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Fleur Noir is a bold expression of dark, artisanal luxury. Its surface is finished in clean gloss with a hand-applied golden and super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with understated elegance and sovereign authority.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown (Duco)',
    top_type: 'Clean Gloss + Hand Applied Golden & Super Black Paint',
    model_number: 'TFN',
    image: '/images/47.webp',
    date_added: '2026-05-17',
    sales_rank: 7,
  },
  {
    id: 48,
    name: 'The Noir Strata',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Noir Strata is a refined expression of dark, artisanal sophistication. Its surface is finished in clean gloss with a golden and super black paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with understated elegance and quiet sovereign authority.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown (Duco)',
    top_type: 'Clean Gloss + Golden & Super Black Paint',
    model_number: 'TNS',
    image: '/images/48.webp',
    date_added: '2026-05-17',
    sales_rank: 6,
  },
  {
    id: 49,
    name: 'The Obsidian Bloom',
    badge: 'new',
    category: 'Coffee Sets',
    description: `Crafted from premium MDF and Fine Board (ZRK) and elevated on ornate fiber molding solid feet with an antique gold finish, The Obsidian Bloom is a masterwork of warmth and ornamental refinement. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, the main coffee table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) while the two matching side tables each measure 24" (L) \u00d7 24" (W) \u00d7 16" (H) \u2014 a sovereignly crafted three-piece ensemble that brings heritage warmth, golden artistry, and distinguished elegance to any living space.`,
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Solid Foot Antique Gold',
    finishing: 'Silky Matte',
    sizing: `Main: 48" \u00d7 30" \u00d7 17" \u00b7 Side: 24" \u00d7 24" \u00d7 16"`,
    color_scheme: 'Chocolate Brown (Duco)',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'OB1',
    image: '/images/49.webp',
    date_added: '2026-05-17',
    sales_rank: 9,
  },
  {
    id: 50,
    name: 'The Royal Lotus',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Royal Lotus is a refined expression of dark, artisanal luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with understated elegance and sovereign authority.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown (Duco)',
    top_type: 'Clean Gloss + Super Black Paint',
    model_number: 'TRL',
    image: '/images/50.webp',
    date_added: '2026-05-17',
    sales_rank: 2,
  },
  {
    id: 51,
    name: 'The Grand Vizier',
    badge: 'new',
    category: 'Coffee Sets',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Grand Vizier is a bold statement of dark, sovereign luxury. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a rich Chocolate Brown Duco colour scheme, the main coffee table is proportioned as a refined square measuring 36" (L) \u00d7 36" (W) \u00d7 17" (H), accompanied by two matching side tables each measuring 24" (L) \u00d7 24" (W) \u00d7 16" (H) \u2014 a sovereignly crafted three-piece ensemble that commands reverence and brings dramatic grandeur to any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'High Gloss',
    sizing: `Main: 36" \u00d7 36" \u00d7 17" \u00b7 Side: 24" \u00d7 24" \u00d7 16"`,
    color_scheme: 'Chocolate Brown (Duco)',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'TGV1',
    image: '/images/51.webp',
    date_added: '2026-05-17',
    sales_rank: 4,
  },
  {
    id: 53,
    name: 'The Meander Square',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) and elevated on ornate fiber molding feet with an antique gold finish, The Meander Square is a refined square coffee table of artisanal distinction. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 42" (L) \u00d7 42" (W) \u00d7 17" (H) \u2014 a perfectly proportioned square silhouette that commands any distinguished living space with quiet, sovereign authority.`,
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Antique Gold Foot',
    finishing: 'Silky Matte',
    sizing: `42" \u00d7 42" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown (Duco)',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'RT',
    image: '/images/53.webp',
    date_added: '2026-05-17',
    sales_rank: 10,
  },
  {
    id: 54,
    name: 'The Atrium Extension',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) and elevated on ornate fiber molding feet with an antique gold finish, The Atrium Extension is a refined expression of artisanal luxury. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with understated elegance and sovereign authority.`,
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Antique Gold Foot',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown (Duco)',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'NS',
    image: '/images/54.webp',
    date_added: '2026-05-17',
    sales_rank: 1,
  },
  {
    id: 55,
    name: 'The Noir Labyrinth',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Noir Labyrinth is a refined expression of dark, artisanal sophistication. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with understated elegance and quiet sovereign authority.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown (Duco)',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'S2',
    image: '/images/55.webp',
    date_added: '2026-05-17',
    sales_rank: 11,
  },
  {
    id: 56,
    name: 'The Walnut Pavilion',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Walnut Pavilion is a refined square coffee table of artisanal distinction. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 36" (L) \u00d7 36" (W) \u00d7 17" (H) \u2014 a perfectly proportioned square silhouette that commands any distinguished living space with quiet, sovereign authority.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'Silky Matte',
    sizing: `36" \u00d7 36" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Chocolate Brown (Duco)',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'WP',
    image: '/images/56.webp',
    date_added: '2026-05-17',
    sales_rank: 13,
  },
  {
    id: 59,
    name: 'The Versailles Cabriolet',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), The Versailles Cabriolet is a bold expression of dark, contemporary luxury. Its surface is finished in clean gloss with a super black and sparkel silver paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Featuring a heavy drawer design for practical elegance, this table is presented in a striking Black and Sparkel Silver Duco colour scheme and measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 perfectly proportioned to anchor any distinguished living space with dramatic contrast and sovereign authority.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Black and Sparkel Silver With heavy Drawer (Duco)',
    top_type: 'Clean Gloss + Super Black & Sparkel Silver Paint',
    model_number: 'VC',
    image: '/images/59.webp',
    date_added: '2026-05-17',
    sales_rank: 3,
  },
  {
    id: 60,
    name: 'Organic Walnut Coffee Table Set',
    badge: 'new',
    category: 'Coffee Sets',
    description: `Crafted from premium MDF and Fine Board (ZRK) with fiber molding foot, the Organic Walnut Coffee Table Set features a clean gloss finish with super black and golden paint. Finished in high gloss for a brilliant mirror-like depth in a Royal Golden High Gloss colour scheme, this set measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a perfectly proportioned silhouette that anchors any distinguished living space with refined elegance.`,
    material: 'MDF + Fine Board (ZRK) With Fiber Molding Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Royal Golden High Gloss',
    top_type: 'Clean Gloss + Super Black & Golden Paint',
    model_number: 'NC',
    image: '/images/60.webp',
    date_added: '2026-05-26',
    sales_rank: 29,
  },
  {
    id: 61,
    name: 'Royal Living Room Collection',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) with imported golden chrome foot, the Royal Living Room Collection features a clean gloss super black painted top. Finished in high gloss with a White and Black High Gloss colour scheme, this set measures 36" \u00d7 60" \u00d7 17" (L \u00d7 W \u00d7 H) \u2014 a magnificent living collection that commands attention with regal sophistication.`,
    material: 'MDF + Fine Board (ZRK) With Imported Golden Chrome Foot',
    finishing: 'High Gloss',
    sizing: `36" \u00d7 60" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'White and Black High Gloss',
    top_type: 'Clean Gloss Super Black Paint',
    model_number: 'GM',
    image: '/images/61.webp',
    date_added: '2026-05-26',
    sales_rank: 30,
  },
  {
    id: 62,
    name: 'White Marble & Gold Coffee Table',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK), the White Marble & Gold Coffee Table features a black and golden marbelized top. Finished in high gloss with a Black and Golden High Gloss (Duco) colour scheme, this table measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sophisticated statement piece that brings timeless elegance to any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK)',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Black and Golden High Gloss (Duco)',
    top_type: 'Black & Golden Marbelize',
    model_number: 'C22',
    image: '/images/62.webp',
    date_added: '2026-05-26',
    sales_rank: 31,
  },
  {
    id: 63,
    name: 'Heritage Carved Coffee Table',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) with imported metal foot, the Heritage Carved Coffee Table features a clean gloss marbelized top. Finished in high gloss with a Royal Golden High Gloss colour scheme, this table measures 36" \u00d7 36" \u00d7 17" \u2014 a timeless carved masterpiece that anchors any distinguished living space with regal elegance.`,
    material: 'MDF + Fine Board (ZRK) With Imported Metal Foot',
    finishing: 'High Gloss',
    sizing: `36" \u00d7 36" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Royal Golden High Gloss',
    top_type: 'Clean Gloss + Marbelize',
    model_number: 'Round M',
    image: '/images/63.webp',
    date_added: '2026-05-26',
    sales_rank: 32,
  },
  {
    id: 64,
    name: 'Executive Dark Coffee Table',
    badge: 'new',
    category: 'Coffee Tables',
    description: `A bold executive-style coffee table set in deep espresso black with clean architectural lines. Shown alongside a matching dark sideboard cabinet, this piece brings a sophisticated, contemporary feel with a Lahore skyline-inspired setting.`,
    material: 'Solid Wood & MDF',
    finishing: 'High Gloss',
    sizing: `60" \u00d7 32" \u00d7 19" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Espresso Black',
    top_type: 'Black Gloss',
    model_number: 'MS-CT-064',
    image: '/images/64.webp',
    date_added: '2026-05-26',
    sales_rank: 33,
  },
  {
    id: 65,
    name: 'Art Deco Living Set \u2013 Teal',
    badge: 'new',
    category: 'Coffee Tables',
    description: `Crafted from premium MDF and Fine Board (ZRK) with fiber molding foot, the Art Deco Living Set features a super black and golden paint top. Finished in high gloss with a Smoked Grey & Golden Black Antique colour scheme, this set measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 an exquisite Art Deco inspired piece that brings refined luxury to any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK) With Fiber Molding Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Smoked Grey & Golden Black Antique',
    top_type: 'Super Black & Golden Paint',
    model_number: 'NC2',
    image: '/images/65.webp',
    date_added: '2026-05-26',
    sales_rank: 34,
  },
  {
    id: 66,
    name: 'Pearl White Chesterfield Set \u2013 Round Table',
    badge: 'new',
    category: 'Coffee Tables',
    description: `A sophisticated pearl white tufted Chesterfield living set paired with a round black marble-top center table on gold legs. Set against a dramatic city night skyline backdrop, exuding penthouse-level opulence.`,
    material: 'Leather & Marble',
    finishing: 'High Gloss',
    sizing: 'Custom',
    color_scheme: 'Pearl White & Black Gold',
    top_type: 'Black Marble Round',
    model_number: 'MS-LS-066',
    image: '/images/66.webp',
    date_added: '2026-05-26',
    sales_rank: 35,
  },
  {
    id: 67,
    name: 'Luxury Tufted Sofa \u2013 Black Marble Table',
    badge: 'new',
    category: 'Coffee Tables',
    description: `An ultra-luxurious living arrangement featuring deep-tufted champagne white leather sofas with a sleek black marble-top rectangular table with thin gold legs. The perfect embodiment of modern luxury with classic character.`,
    material: 'Leather & Sintered Stone',
    finishing: 'Gold Trim',
    sizing: 'Custom',
    color_scheme: 'Champagne White & Black Marble',
    top_type: 'Black Marble Rectangular',
    model_number: 'MS-LS-067',
    image: '/images/67.webp',
    date_added: '2026-05-26',
    sales_rank: 36,
  },
  {
    id: 69,
    name: 'Modern Drum Coffee Table Set',
    badge: 'new',
    category: 'Coffee Sets',
    description: `Crafted from premium MDF and Fine Board (ZRK) with fiber molding foot, the Modern Drum Coffee Table Set features a clean gloss finish with super black and silver paint. Finished in high gloss with a Silver Grey & Black Antique colour scheme, this set measures 48" (L) \u00d7 30" (W) \u00d7 17" (H) \u2014 a sophisticated statement piece for any distinguished living space.`,
    material: 'MDF + Fine Board (ZRK) With Fiber Molding Foot',
    finishing: 'High Gloss',
    sizing: `48" \u00d7 30" \u00d7 17" (L \u00d7 W \u00d7 H)`,
    color_scheme: 'Silver Grey & Black Antique',
    top_type: 'Clean Gloss Super Black & Silver Paint',
    model_number: 'NC1',
    image: '/images/69.webp',
    date_added: '2026-05-26',
    sales_rank: 38,
  },
];
